name: Sync Fork with Upstream

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Add upstream remote
      run: git remote add upstream https://github.com/microsoft/dicom-server.git

    - name: Fetch from upstream
      run: git fetch upstream

    - name: Update local main
      run: |
        git checkout main
        git merge upstream/main

    - name: Push updates
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
