name: Sync Fork with Upstream

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Add upstream remote
      run: git remote add upstream https://github.com/microsoft/dicom-server.git

    - name: Fetch from upstream main
      run: git fetch upstream main

    - name: Check for changes from upstream
      id: upstream_changes
      run: |
        if git diff --quiet main upstream/main; then
          echo "No new changes from upstream"
          echo "::set-output name=changes::false"
        else
          echo "New changes found from upstream"
          echo "::set-output name=changes::true"
        fi

    - name: Update local main from upstream
      if: steps.upstream_changes.outputs.changes == 'true'
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories

    - name: Push updates
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
